export default {
  login: "SeytkhanB",
  id: 95151081,
  node_id: "U_kgDOBavj6Q",
  avatar_url: "https://avatars.githubusercontent.com/u/95151081?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/SeytkhanB",
  html_url: "https://github.com/SeytkhanB",
  followers_url: "https://api.github.com/users/SeytkhanB/followers",
  following_url: "https://api.github.com/users/SeytkhanB/following{/other_user}",
  gists_url: "https://api.github.com/users/SeytkhanB/gists{/gist_id}",
  starred_url: "https://api.github.com/users/SeytkhanB/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/SeytkhanB/subscriptions",
  organizations_url: "https://api.github.com/users/SeytkhanB/orgs",
  repos_url: "https://api.github.com/users/SeytkhanB/repos",
  events_url: "https://api.github.com/users/SeytkhanB/events{/privacy}",
  received_events_url: "https://api.github.com/users/SeytkhanB/received_events",
  type: "User",
  site_admin: false,
  name: "Seytkhan",
  company: null,
  blog: "",
  location: "Almaty, Kazakhstan",
  email: null,
  hireable: null,
  bio: "Frontend-developer React.js",
  twitter_username: "SeytkhanB",
  public_repos: 32,
  public_gists: 0,
  followers: 0,
  following: 5,
  created_at: "2021-11-27T23:55:16Z",
  updated_at: "2022-10-19T10:18:06Z"
  }